name: CI
on:
    push:
        branches: [md3]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up jdk
              uses: actions/setup-java@v3
              with:
                  distribution: "adopt"
                  java-version: "17"

            - name: Setup client
              env:
                  CLIENT_INFO: ${{ secrets.CLIENT_INFO }}
              run: |
                  echo -e "${CLIENT_INFO}" > client.properties
              shell: bash

            - name: Change wrapper permissions
              run: chmod +x ./gradlew
              shell: bash
            - name: Checkout submodules
              run: git submodule update --init --recursive
              shell: bash
            - name: Download app deps
              run: ./gradlew androidDependencies
              shell: bash

            - name: Build
              run: ./gradlew clean assembleRelease
              shell: bash

            - name: Fetch public keystore
              run: wget https://github.com/tytydraco/public-keystore/raw/main/public.jks
              shell: bash

            - name: Sign release APK
              run: |
                  apksigner="$(find $ANDROID_SDK_ROOT/build-tools -name apksigner | sort -r | head -n 1)"
                  "$apksigner" sign --ks public.jks --ks-key-alias public --ks-pass pass:public --key-pass pass:public --in ./app/build/outputs/apk/release/app-release-unsigned.apk --out ./app/build/outputs/apk/release/app-release.apk
              shell: bash

            - name: Upload signed release APK
              uses: actions/upload-artifact@v2
              with:
                  name: gh4a-release
                  path: ./app/build/outputs/apk/release/app-release.apk
